import pyautogui as aut
aut.hotkey('win','r')
aut.sleep(0.5)
aut.write('chrome')
aut.sleep(1)
aut.press('enter')
aut.moveTo(449,656)
aut.click()
aut.hotkey('win', 'r')
aut.sleep(0.5)
aut.write('chrome')
aut.sleep(1)
aut.press('enter')
aut.sleep(2)
aut.moveTo(177,64)
aut.click()
aut.sleep(1)
aut.write('youtube', interval=0.3)
aut.press('enter')
aut.sleep(2)
aut.moveTo(748,176)
aut.click()
aut.sleep(2)
aut.write('peppa pig')
aut.press('enter')
aut.sleep(2)
aut.moveTo(731,626)
aut.click()
aut.sleep(2)